version: '3.1' 

services:
  # Wordpress application
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    links:
      - db:db
    restart: always
    volumes:
      - ./app:/var/www/html
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_db_password
      WORDPRESS_DB_HOST: db:3306
    networks:
      - wpsite

  # PHP my admin
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - wpsite

  # Database
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      # for existing database sql file
      # -./db:docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress 
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_db_password
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  app:
  db: